### ISSUE TITLE
Problem with subscriber (404 always)

### ISSUE THREAD

**Issue by slimus** [slact/nchan#102]
Hello!
My config is 
```
...
location ~ /sub/(.*) {
    set $access_token '';
    if ($access_token = '') {
       set $access_token $arg_access_token;
    }
    if ($access_token = '') {
        set $access_token $1;
    }
    push_subscriber      long-poll;
    set $push_channel_id $access_token;
}
...
```
And all my requests (for example http://example.com/sub/abc123qwe) return 404 page and error "No channel id provided"

My config is incorrect? Can I resolve this issue? 
Before I used nginx push stream module but compile nginx is very problem for all my clients.
Thanks!

**Comment by slact** [comment]
I think this is a configuration issue. nginx's if statements aren't necessarily executed before directives in a context. see https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/

**Comment by slimus** [comment]
slact, thanks for your comment! I read this topic but i don't known how i can write this without if statements.
We used to use other module for push stream and this config worked well.

**Comment by slact** [comment]
Ah, I think I know why it worked, too. This is mostly a guess from memory, but I'm about 70% sure this is why. It's been a while since I've read through the push-stream module code -- (did you know that it's a fork of the push module?) -- but as I recall, they use a directive instead of a variable to set the channel id. Custom directives are processed after variables in the guts of nginx, so such a config, even with a bunch of "evil ifs" just might have worked because of this.

If you show me the rest of the config, I might be able to help you rewrite it. You can probably get around this issue by using the [push_channel_group](https://pushmodule.slact.net/#config-push_channel_group) directive.

**Comment by slact** [comment]
correction -- it's because nginx needs special authorization to use a directive in an if statement. the new `nchan_channel_id` directive will work in an `if`
