### ISSUE TITLE
nchan vs nginx-push-stream-module?

### ISSUE THREAD

**Issue by kajmagnus** [slact/nchan#116]
Hi, can I ask, what are the differences between nchan and nginx-push-stream-module?
(https://github.com/wandenberg/nginx-push-stream-module)

Here someone has asked about this at StackOverflow:
http://stackoverflow.com/questions/7815945/which-module-for-nginx-is-the-best-for-http-push

(There's just one outdated answer that mentions the older https://pushmodule.slact.net/ and that it doesn't support websocket)

(People sometimes mention that nginx-push-stream-module is a fork of http-push-module — still, what are the differences :-) — why did you "upgrade" to nchan instead of pulling in into http-push-module the stuff in the fork)

**Comment by kajmagnus** [comment]
Now I googled a bit more about this and found this:

_"Yes, this is a different project, although they are related. Push Stream is a fork of my Nginx HTTP Push Module, so they both descend from the same original codebase. Push Stream uses a blocking concurrency model, whereas Nhan is completely non-blocking. In theory, this means Nchan should scale better. In practice, I haven't benchmarked it heavily enough yet to see a divergence.
Besides that, nchan and Push Stream offer different feature sets. For example, Nchan has horizontal scaling and persistence through redis, whereas push stream has customizable message transforms. There are other differences as well, but that would take a whole article to elaborate. I should probably write it soon."_

here: https://news.ycombinator.com/item?id=10685946

**Comment by slact** [comment]
The push-stream form is a series of incremental patches to the original Push Module codebase. They diverged about 4 years ago, and there was no way for me to integrate their work while also cleaning up and refactoring the core codebase. However, I do use some snippets of their code in Nchan. 

I renamed the Push Module into Nchan because it underwent a complete architectural rewrite, and I threw in so many new features.

**Comment by kajmagnus** [comment]
Thanks :-)
