### ISSUE TITLE
Would publish-to-multiple-channels make sense?

### ISSUE THREAD

**Issue by kajmagnus** [slact/nchan#119]
Hi, currently in the docs: _"Publishing to multiple channels from one location is not supported"_.

I think I'd like each user to subscribe to events via their user id, and then in the app server, push to each individual user channel everything I know that user is interested in. Rather than having each user subscribe to many different channels, one for each thing it's interested in.

Now, if many users look at the same page, I would want to push the same events to all these users. I'd like to send one single POST from the app server to Nginx, rather than one-per-user-looking-at-the-page.

(( (In this parenthesis: Motiviation for one-channel-per-user & hence publish-to-many-channels.) I could instead have the users listen on the page id instead, for example, and publish to a page id channel. This seems a little bit more complicated to me, because I need the per-user channels anyway. And some per-page events should be sent to moderators and/or admins only, so I would need many types of channels per page. And also if I have say a Websocket connection already, I think I'd like to dynamically change which events get sent to that channel, without the browser having to abort that connection and create another one. And then I think I want just one channel per user rather than one channel per thing the user cares about. — And what about this: a user has subscribed to events for a page. But then a moderator decides that the user may not see that page. However, the user has been granted access to the page channel already. Now, it seems it would have been easier to have a per user channel instead, so the server didn't need to expose any page-channel at all. ))

I'm thinking publishing-to-many-channels could be done by POSTing data to Nginx that looks like this:

```
channel-id-1
channel-id-2
channel-id-3

the-data-to-publish
```

So, first channel ids, one one each line. Then a blank line. Then everything below is the message to publish to all channels listed above.

Would it make sense to some day support publishing to multiple channels? Or is there something about PubSub that it seems I've misunderstood and I'm doing it in the wrong way? (I'm new to all this)

**Comment by slact** [comment]
It's actually quite easy to implement publish-to-many-channels functionality, but not in the way you propose. I simply didn't see a good enough use case to implement it. Basically, I fear that publish-to-many functionality would encourage 'bad' design decisions, as I will elaborate below. Of course, I might be wrong about this, and I'm quite open to having my mind changed on the matter.

> I would want to push the same events to all these users. I'd like to send one single POST from the app server to Nginx, rather than one-per-user-looking-at-the-page.

That's plausible, but bear in mind that this would be limited to 255 max channel IDs per POST. A better solution would be for all the users to subscribe to their own user channels, and the channel of the page they are looking at. Then your app would send one POST to the page's channel, rather than one per each user-per-page.

Let's consider the other use cases you gave:

>  I could instead have the users listen on the page id instead, for example, and publish to a page id channel. This seems a little bit more complicated to me, because I need the per-user channels anyway. And some per-page events should be sent to moderators and/or admins only, so I would need many types of channels per page.

Like I explained above, channels are cheap. Two channels (one for regular users, one for admins) per page is not a problem. This adds no application server complexity (you just publish to the correct channel id -- page-users, page-admins, or user), and just a little more client complexity (subscribe to user channel and page's admin or user channel on one connection), reconnecting when going to a new page.

> And also if I have say a Websocket connection already, I think I'd like to dynamically change which events get sent to that channel, without the browser having to abort that connection and create another one.

Why is this the case? Is it because there's no mechanism for resuming a Websocket connection, or are you concerned with the handshake overhead? If the former, I would not recommend using Websockets for receiving application events, and instead suggest EventSource or Long-Polling over HTTP/2 -- they have less overhead, and can be reconnected with a no-loss and no-repetition guarantee. If the latter, I don't think I have much to offer other than the websocket handshake over an existing TLS connection is already pretty cheap.

> And then I think I want just one channel per user rather than one channel per thing the user cares about.

Why not both?


> And what about this: a user has subscribed to events for a page. But then a moderator decides that the user may not see that page. However, the user has been granted access to the page channel already. Now, it seems it would have been easier to have a per user channel instead, so the server didn't need to expose any page-channel at all.

This is best handled through the authorization mechanisms available. If you don't want to expose the page-channel id, you can use the https://nchan.slact.net/details#authenticate-and-hide-the-channel-id-with-x-accel-redirect mechanism. 

If you per-message granularity for subscriber authorization, use long-polling in combination with either the above-mentioned X-Accel-Redirect mechanism or the simpler https://nchan.slact.net/details#authenticate-with-nchan_authorize_request mechanism can be used to ensure a subscriber is still permitted after every received message. 

> I'm thinking publishing-to-many-channels could be done by POSTing data to Nginx that looks like this:  
  channel-id-1
  channel-id-2
  channel-id-3  
>
  the-data-to-publish
> 
> So, first channel ids, one one each line. Then a blank line. Then everything below is the message to publish to all channels listed above.


I'm very much opposed to this, because I'm trying to remain as content-agnostic as possible, so I'd rather not do anything like that in response to the message body. If you want to do something like this, just use long-polling. There is only the headers overhead (No TCP reconnection as HTTP/1.1 connections are keep-alive by default), and even that is removed with HTTP/2.


> Would it make sense to some day support publishing to multiple channels? Or is there something about PubSub that it seems I've misunderstood and I'm doing it in the wrong way? (I'm new to all this)

I don't think you've misunderstood anything, you just haven't realized the advantage of cheap channels. And yes, if you need it, I can add publisher multiplexing in the same way as subscriber multiplexing. Beyond that, it's going to take a lot more to convince me.

**Comment by kajmagnus** [comment]
Hi Slact / Leo, Thanks for your reply. I think everything boils down to that I want the app server to dynamically, and sometimes instantly, modify what data gets sent to a user, and that in the end results in (I think) publish-to-many-channels.

1.

I want the app server to be able to immediately stop sending messages from a certain chat room to the browser. When I wrote previously that_"a moderator decides that the user may not see that page.  However, the user has been granted access to the page channel already"_ — what I had in mind, was to kick out a user who is currently connected to a chat room. Because up until now the user was allowed to access the chat room, but now suddenly an admin removes him/her from that chat room, so now s/he should be kicked immediately.

And the only way to do that, as far as I can tell, is to have one channel per user, and have the app server filter what gets sent to that channel — the app server would just stop sending [data about that chat room] to the kicked user's channel.

( You wrote: _"If you [want] per-message granularity for subscriber authorization, use long-polling in combination with either the above-mentioned X-Accel-Redirect mechanism or the simpler https://nchan.slact.net/details#authenticate-with-nchan_authorize_request mechanism can be used to ensure a subscriber is still permitted after every received message"_ — however that might still send one message back to the browser that the user shouldn't see. Actually at work one of the few times when we removed someone from a chat room, the chat messages directly afterwards was about why that user was removed. (The reason: he was added by mistake.) So I think it's fairly likely that if just one message too much gets sent to the kicked user, that message will be something about him/her that the others in the chat room thought was written in private. )

( [zzwwqq] If it was possible to send a message to Nchan to remove a user from a per-chat-room-channel, that might work just as fine. ... Or perhaps no it wouldn't? Because: 1) what if the request to Nginx to unsubscribe the user fails in some way, so that the user stays connected. For example, the app server might get restarted just before it sends the request to Nginx.  Then, when the server is online again, the user would still be connected to the chat channel, and private data might be leaked to the user. (Adding logic to deal with unsubscriptions + server restats, seems complicated.) And 2) race conditions if a browser resubscribes to a channel at the same time as the server sends an unsubscribe message to Nchan. )

( These are related to authenticating & authorizing when connecting, but cannot instantly kick an already connected user, it seems to me:  
https://nchan.slact.net/details#authenticate-and-hide-the-channel-id-with-x-accel-redirect  
and https://nchan.slact.net/details#authenticate-with-nchan_authorize_request )

2.

Re this: I wrote: _"I think I'd like to dynamically change which events get sent to that channel, without the browser having to abort that connection and create another one"_. You wrote: _"Why is this the case? Is it because there's no mechanism for resuming a Websocket connection, or are you concerned with the handshake overhead?"_

I think that was because of imagined overhead, plus a 3rd alternative: sometimes the server knows when the user should get new types of events or stop getting some events. And if the browser is to send a new request to listen on the correct set of channels in order for this to happen, then the server needs to first tell the browser what request it should send back to the server. — I'd rather have the server deal with this automatically without round-tripping to the browser (because: simpler).

(How can the server know when the browser should start getting data about new types of events? But the browser doesn't always know? Example: a colleague creates a new chat room and adds me. The server, but not my browser, knows that this has happened.)

***

Did this affect how you look at publish-to-many-per-user-channels-at-once and good/bad design decisions?

(I think the main point is that the server wants to instantly stop (or start) sending some events to the user, because of security (section 1 above) and simplicity (section 2). And, when Nchan manages channels & subscribers, this leads to one-channel-per-user and the app server filtering what gets sent to that channel (because of [zzwwqq]). Which leads to push-to-many.)

**Comment by slact** [comment]
I still think what you want to do can be achieved efficiently without adding your proposed functionality. Here's how: 

> I want the app server to be able to immediately stop sending messages from a certain chat room to the browser. [...] Because up until now the user was allowed to access the chat room, but now suddenly an admin removes him/her from that chat room, so now s/he should be kicked immediately.
> 
> And the only way to do that, as far as I can tell, is to have one channel per user, and have the app server filter what gets sent to that channel — the app server would just stop sending [data about that chat room] to the kicked user's channel.

That is the most obvious way, but it is not the _only_ way. I'll give one example of how to do it, but there are probably other ways as well.

The setup is that you have a location for a user's channel, an _internal_ location for a chatroom (one inaccessible to subscribers except via an internal Nginx redirect, and an upstream location for using the [X-Accel-Redirect mechanism](https://nchan.slact.net/details#authenticate-and-hide-the-channel-id-with-x-accel-redirect). Your Nginx config might look something like:

```nginx

server {
  listen 80;
  #public-facing server block
  location = /sub {
    #public subscriber endpoint
    proxy_pass http://app_server/internal_subscriber_redirect;
    proxy_set_header    Host            $host;
    proxy_set_header    X-Real-IP       $remote_addr;
    proxy_set_header    X-Forwarded-For $remote_addr;
  }

  location ~ /sub/internal {
    internal;
    #X-Accel-Redirect endpoint, inaccessible except via an internal redirect
    nchan_subscriber;
    nchan_channel_id user/$arg_user chat/$arg_chat;
  }
}

server {
  listen 127.0.0.1:8080;
  #local network or localhost-only server block, inaccessible from the outside
  location ~ /pub/(user|chat)/(.+)$ {
    nchan_publisher;
    nchan_channel_id $1/$2
  }
}
```

So that's one public subscriber endpoint, at `/sub`, which redirects to the app for authentication. 

The app receives a GET /internal_subscriber_redirect with accompanying headers, and validates the user's session through the included cookie headers. Additional parameters can be passed via query string, such as the requested chat room. If the session is invalid or the user is disallowed in the requested chatroom, the app can return a `400 Forbidden` which in turn is forwarded by Nginx to the subscriber.

If the session is valid and the chatroom requested is permitted, the Application returns a `200 OK` with two additional headers. This is where the magic happens:
```
X-Accel-Redirect: /sub/internal?user=USERID&chat=CHATID
X-Accel-Buffering: no
```
Nginx interprets this response as an internal redirect to `/sub/internal?user=USERID&chat=CHATID`, which is a subscriber endpoint for two channels, `user/USERID` and `chat/CHATID`. (Remember, this URL cannot be accessed directly from the outside.) Now the subscriber performs its handshake (if it's a websocket sub) and listens to messages on both channels.

So let's say the user now needs to be kicked out of the CHATID chatroom. I just read over my documentation, and it looks like I failed to mention this important behavior, but `DELETE` requests, which have the effect of kicking out all subscribers of a channel (as well as deleting the channel's messages), are forwarded to the multi-channel subscribers as well. (I'll make sure to explicitly document this). So a DELETE request to `/pub/user/USERID` will kick the subscriber subscribed at `/sub/internal?user=USERID&chat=CHATID`. 

If a users is _banned_ from a chat, upon trying to reconnect via `/sub` -- which forwards the request to the app for authorization -- he can receive either a `400 Forbidden` response or a `200 OK with an `X-Accel-Redirect: /sub/internal?user=USERID&chat=null`, and maybe a message notifying the user that he is banned from CHATID published to `user/USERID`.


So the magic here is `X-Accel-Redirect`. Your app is responsible for authenticating the user and his access to a chatroom, so no amount of clientside trickery will get around your serverside authentication mechanisms. 

If you don't want to delete the user's channel, you could use this location instead:
```nginx 

  location ~ /sub/internal {
    internal;
    #X-Accel-Redirect endpoint, inaccessible except via an internal redirect
    nchan_subscriber;
    nchan_channel_id user/$arg_user kickuser/$arg_user chat/$arg_chat;
  }

#internal server location:
  location ~ /pub/(user|chat|kickuser)/(.+)$ {
    nchan_publisher;
    nchan_channel_id $1/$2
  }

```
That is, an `X-Accel-Redirect: /sub/internal?user=USERID&chat=CHATID` will subscribe the client to `user/USERID`, `kickuser/USERID`, and `chat/CHATID`. Then, a DELETE to `/pub/kickuser/USERID` will kick out the user without losing any messages in the user/USERID channel.

So that's one way to do it. Because I think your use case is covered by the mechanism I've described, I'm still not convinced the functionality you proposed is necessary. Does this cover your use case? Is the solution too complicated? Let me know what you think.

**Comment by slact** [comment]
Oh, and to address your second point:
> How can the server know when the browser should start getting data about new types of events? But the browser doesn't know? Example: a colleague creates a new chat room and adds me. The server, but not my browser, knows that this has happened.

Again, this can be done with the above mechanism, using a DELETE `kickuser/USERID` request, or a more appropriately named  `DELETE reconnect/USERID` As soon as a user is invited into a new chat, his client's subscriber request is terminated and he initiates it again automatically. The app then sends an appropriate `X-Accel-Redirect` header that includes the new chatroom, and the user is now listening for the new chatroom's messages.

**Comment by kajmagnus** [comment]
Hi again,

> Does this cover your use case?

Yes I think so.

> Is the solution too complicated?

Hmm, well, what I'm thinking right now is that if Nchan was written in Java/Scala, and Nginx & Nchan were easy to debug & unit test etc, then I'd consider tweaking Nchan, if needed because of performance — rather than start using one-channel-per-chat-room. Partly because the Nchna stuff mentioned above does look a bit complicated, and also because of 3 and 4 below:

3.

If the app server restarts just after it has kicked the user from a chat room, and then because of the restart, the `DELETE` to the Nchan channel never happens, then the user might continue to get chat messages when the server is online again, although s/he was kicked. If this happens or not — I guess it depends, and is very unlikely. But it's something I would think a bit about.


4.

>Oh, and to address your second point:
 
>>How can the server know when the browser should start getting data about new types of events? But the browser doesn't know? Example: a colleague creates a new chat room and adds me. The server, but not my browser, knows that this has happened.

>Again, this can be done with the above mechanism, using a DELETE kickuser/USERID request, or a more appropriately named DELETE reconnect/USERID As soon as a user is invited into a new chat, his client's subscriber request is terminated and he initiates it again automatically. The app then sends an appropriate X-Accel-Redirect header that includes the new chatroom, and the user is now listening for the new chatroom's messages.

I think there's a problem here: `subscriber request is terminated and he initiates it again automatically` — namely that in between, some messages might be lost, if WebSocket is in use (right? Since it doesn't buffer messages). However if the server just starts sending messages for the new chat channel too, no messages will be lost. ((The browser is going to receive messages for many chat rooms at the same time, so that it has an up-to-date view of all of them and can switch between them instantly.))

For what it's worth, Slack (a popular chat app) apparently creates just 1 WebSocket connection and then keep using it forever. It never closes and reopens to listen on a new chat room. (As far as I could tell when I inspected Slack in Chrome Dev Tools for a little while.)

\***

This isn't clear to me: (perhaps other people who read the docs later also will wonder?)

> ... DELETE requests, which have the effect of kicking out all subscribers of a channel (as well as deleting the channel's messages), are forwarded to the multi-channel subscribers as well

If a user subscribes to `/sub/user-USERID/chat-CHATID`, where  channel `chat-CHATID` is shared between many subscribers, and then:

If I send a DELETE to `/pub/user-USERID` then is the user kicked from both channels `user-USERID` and `chat-CHATID`? And no other users kicked from `chat-CHATID`?

If I send a DELETE to `/pub/user-CHATID` then all users are kicked from the chat right?

If I send a DELETE to `/pub/user-USERID/chat-CHATID`, then what happens? :-)

\**

(P.S. homepage docs typo: _"Applicable only if a push_subscriber is present in this or a child context"_ — should be "nchan_subscriber" not "push_subscriber", nowadays, I think)

Best regards

**Comment by slact** [comment]
Ok, I'm convinced that this needs to be a feature. I'll address your points first, then cover what I intend to implement.

> 3. If the app server restarts just after it has kicked the user from a chat room, and then because of the restart, the DELETE to the Nchan channel never happens, then the user might continue to get chat messages when the server is online again, although s/he was kicked. If this happens or not — I guess it depends, and is very unlikely. But it's something I would think a bit about.

I don't see a way around app server failure. Either the app notifies nchan to kick a user -- which is vulnerable to app server failure, or the user's client is responsible for leaving -- which is insecure. 

> 4. [...]  I think there's a problem here: subscriber request is terminated and he initiates it again automatically — namely that in between, some messages might be lost, if WebSocket is in use (right? Since it doesn't buffer messages). 

Quite right. Lost messages would indeed be an issue in this case.

> This isn't clear to me: (perhaps other people who read the docs later also will wonder?) [...]

Yeah, I could word that a bit better.

> P.S. homepage docs typo

Thanks

**Comment by slact** [comment]
Now, onto the feature proposal: Currently, a websocket subscriber that publishes anything gets disconnected. This is different from websockets connecting via pubsub locations, where publishing is treated as publishing a message. 

Rather than treating WS subscriber-only clients sending data as invalid and disconnecting them, I could treat the message as a delimiter-separated list of channels to subscribe to, perhaps with a newline delimiter by default. This feature would be enabled by a config setting (which I have yet to name). So to switch a websocket subscriber to a set of new channels, send a newline-separated list of channels to be subscribed to.

This makes sense to me because EventSource and Long-Polling connections can be restarted without loss of messages, whereas for Websockets this is not the case. This feature would make it possible, and it would not interfere with existing functionality.

What do you think?

**Comment by kajmagnus** [comment]
> I don't see a way around app server failure. Either the app notifies nchan to kick a user -- which is vulnerable to app server failure, or the user's client is responsible for leaving -- which is insecure.

I think the app server can 1) save in its database that it intends to unsubscribe the user. 2) unsubscribe the user. 3) delete the I'm-going-to-unsubscribe-that-user entry from the database.

And if the server crashes/restarts so that step 2 fails, then, when it starts again, it checks the database for non-deleted entries from step 1 above, and unsubscribes those users.

Seems like complicated though. And writing test code that verifies that it works, might be even more complicated :-P

> Rather than treating WS subscriber-only clients sending data as invalid and disconnecting them, I could treat the message as a delimiter-separated list of channels to subscribe to

> EventSource and Long-Polling connections can be restarted without loss of messages, whereas for Websockets this is not the case. This feature would make it possible, to switch channels with a no-loss, no-repetition guarantee (like ES and long-poll)

1) This won't work for pub-sub WS clients who want to send messages over WS to the server? What about a separate POST request to the WS location, with post data = the new set of channels? That should work for WS clients that publish data too.

2) However, if the server wants to kick the user from one channel: This approach still leaves the user's client responsible for leaving, right? So it's insecure? (Unless the server forcibly unsubscribes the client, but then: perhaps messages lost, for honest clients)

**Comment by slact** [comment]
> [...]
> 2) However, if the server wants to kick the user from one channel: This approach still leaves the user's client responsible for leaving, right? So it's insecure? (Unless the server forcibly unsubscribes the client, but then: perhaps messages lost, for honest clients)

Yeah, that's true, and definitely not acceptable in your situation. I guess my proposed feature doesn't help in your case after all.

Okay, so here's my last-ditch question: why do you need to use websockets? What you're trying to do can be fairly easily done with long-polling / SSE, plus you get no-loss, no-repeat guarantees if the connection is unexpectedly interrupted. 

I'm still very uncomfortable introducing content-dependent semantics for POST requests to publisher endpoints. Conceptually, I would be okay with doing this for a new kind of endpoint location ('control' rather than 'publisher' for example), but that might might open a whole other can of worms of hard-to-document functionality and feature bloat. 

So I'm still not quite sure, so I'd like to know why you must use websockets.

**Comment by kajmagnus** [comment]
> why do you need to use websockets?

Actually currently I don't. In the fairly distant future, though, if the web app gets popular, I would think/guess that it'd be good to have the option to switch to WS, to reduce the number of requests to Nginx. At least it feels like good-to-know if it will-be / perhaps-will-be possible to do that, in the future.


> new kind of endpoint location

A new endpoint is a good idea I think. I had in mind a name like `nchan_multi_publisher`, and ... but ...

\***

...Please keep in mind that the title of this thread is _"Would publish-to-multiple-channels make sense?"_  — but not _"Can we please add ...?"_ :-)  I was mainly wondering if publish-to-many is something that would make sense to add, some time in the future. 

I'm thinking that for now the do-nothing & wait-and-see approach is a good one. Then, later on, perhaps more people will say what they need, and then it'll be easier to build something that many people want.

However I suspect that fairly many people don't think about things like the ones we discussed above. I would think they might build something that is a little bit not-totally-safe, without realizing that they could have made good use of one-channel-per-user & publish-to-many-channels.

To avoid that, perhaps it would make sense to add on the docs page _documentation_ about a publish-to-multi Nchan location, and how it would work? — But without actually implementing it. And telling them to +1 in a GitHub issue? if they want this feature

(If it's visible in the docs, people might stop and think about it. Otherwise I wonder if people instead fairly often would adjusts their own design to use only the features they see exists already.)

**Comment by slact** [comment]
> ...Please keep in mind that the title of this thread is "Would publish-to-multiple-channels make sense?" & "Would it make sense to some day support ...?" — but not "Can we please add ...?" :-) I was mainly wondering if publish-to-many is something that would make sense to add, some time in the future. 

Yeah, true. You've convinced me, this feature will be available in the next version.

**Comment by slact** [comment]
Publishing to multiple channels is now supported in v0.98. see https://nchan.slact.net#channel-multiplexing . Thank you for the in-depth discussion about the feature!

**Comment by kajmagnus** [comment]
Okay. And thanks for the feature :- )  I'll start using it soon (some week?), working with other stuff now
