### ISSUE TITLE
Last-Modified is the same as If-Modified-Since

### ISSUE THREAD

**Issue by brunoqc** [slact/nchan#126]
If I do a GET /sub with a `Last-Modified` value I get the value I already know about with the same `If-Modified-Since`.

I was under the impression that you can't receive a `Last-Modified` value equal or inferior that the supplied `If-Modified-Since` value.

curl output:
```
> GET /sub HTTP/1.1
> If-Modified-Since: Wed, 27 Jan 2016 19:47:49 GMT
[...]
< HTTP/1.1 200 OK
< Date: Wed, 27 Jan 2016 19:50:50 GMT
* Server nginx is not blacklisted
< Server: nginx
< Strict-Transport-Security: max-age=15768000
< Content-Type: application/json
< Content-Length: 168
< Last-Modified: Wed, 27 Jan 2016 19:47:49 GMT
< Etag: 1
< Vary: If-None-Match,If-Modified-Since
< X-Frame-Options: SAMEORIGIN
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Keep-Alive: timeout=15, max=100
< Connection: Keep-Alive
```

**Comment by slact** [comment]
From the documentation: 

> The long-polling subscriber walks through a channel's message queue via the built-in cache mechanism of HTTP clients, namely with the "Last-Modified" and "Etag" headers. Explicitly, to receive the next message for given a long-poll subscriber response, send a request with the "If-Modified-Since" header set to the previous response's "Last-Modified" header, and "If-None-Match" likewise set to the previous response's "Etag" header.

( https://nchan.slact.net/#long-polling )

A message's id is encoded into the `Last-Modified` _and_ `Etag` headers (or, for requests, `If-Modified-Since` _and_ `If-None-Match`), so it's perfectly okay to have a response with a `Last-Modified` equal to the request's `If-Modified-Since`, provided that the `If-None-Match` headers is _not_ equal to the response's `Etag`.  This is necessary when more than one message is published to a channel per second. (It's also used for multi-channel subscribers.)

If you don't want to deal with keeping track of messages with two cache headers, you can configure Nchan to use only the `Etag`/`If-None-Match` header by enabling the `[nchan_subscriber_compound_etag_message_id](https://nchan.slact.net/#nchan_subscriber_compound_etag_message_id)` config setting.

**Comment by brunoqc** [comment]
I missed that from the documentation. Sorry about that.

Thanks. It works perfectly now.
