### ISSUE TITLE
Support for Memcached and other storage engines

### ISSUE THREAD

**Issue by iNDicat0r** [slact/nchan#144]
Hello,
From your documentation i can see that there is no support for memcached(only redis) as the storage engine. It would be nice to have this feature implemented since many frameworks like laravel, django have default support of memcached and more important, scaling will be possible for apps with memcached requirement.

Regards

**Comment by slact** [comment]
From what I understand, there is no efficient way to use memcached as a storage engine. This is because memcached does not have a pub/sub mechanism     which is needed to synchronize workers and different nginx instances.

**Comment by iNDicat0r** [comment]
Sounds interesting. Does this implies that the communication between nginx and redis is a 2-way communication, and redis is not only for storage but used for pub/sub events listening by nginx workers?

**Comment by slact** [comment]
Yes. Think of it this way: There are two nginx instances connected to the same redis server. A message is published from one server. How does the other server become aware of it? Either it must poll the redis server, or it must receive a notification from it, as the two nginx servers cannot communicate with each other directly. 

The same mechanism is used for the workers as well. Although technically there is a mechanism for interprocess communication, it is used only for the in-memory storage engine (which also serves as a cache layer for the redis storage engine)

**Comment by iNDicat0r** [comment]
Nice explanation. So technically your module can perfectly scale using more nginx instances while the nginx push stream module isnt capable of what your module achieves. My question is what happens if a pub command is triggered directly on the redis server or through an internal software(without going through the nginx publish url) would your module retrieve that data which was not sent through nginx?

**Comment by slact** [comment]
There is currently no mechanism to publish messages directly through redis, because this is not a trivial process. Here's the script to publish a message via redis: https://github.com/slact/nchan/blob/master/src/store/redis/scripts/publish.lua 

If you were to try publishing a message directly through redis, you'd probably break something. 
Even if you use the publish script linked above, if you get the config parameters wrong, there may be problems later on.

I could, in the future, expose this functionality through calling a lua script directly, but I don't think this is a particularly good idea as the script's hash will change every time the code itself changes, making a stable API impossible.

Why are you interested in publishing via redis directly rather than going through a publisher URL? Just curiosity, or do you have a particular use case in mind?

**Comment by iNDicat0r** [comment]
I have got gearman workers which are doing cpu intensive jobs and since I am using abit of redis within my c/c++ I was thinking of publishing the progress events directly using the c redis client api but its not a big deal and can be done normally using the post to nginx location.

**Comment by slact** [comment]
Understood. By the way, in the future, nchan could support things like Apache Kafka and PostgreSQL (but not MySQL). That's not for a while though, unless someone cares to sponsor the development of any of these features.

**Comment by iNDicat0r** [comment]
That sounds good. In my opinion mongodb would be a very good choice for your case in terms of scalability, functionality ( there is sub/pub in mongodb) and performance.

**Comment by slact** [comment]
Oh yeah, MongoDB is also a possibility.
