### ISSUE TITLE
Problem with redis and expired messages

### ISSUE THREAD

**Issue by MrDefacto** [slact/nchan#247]
Hi,

On newest github version (i didn't check previous) there is problem in some cases when messages expires.

This is what i've found in nginx-error.log:

Assertion failed: (status == NGX_OK), function redis_receive_channel_auth_check_callback, file /usr/ports/www/nginx/work/nchan/src/store/memory/ipc-handlers.c, line 659.

Best regards,

**Comment by slact** [comment]
there should be another error somewhere above that line in the log. Do you see it?

**Comment by slact** [comment]
Please rebuild from master and wait until you get this error again. I haven't fixed it, but I needed to modify the code so that the cause of the error will show in your log.

Once you see this error again, show me the error log. There should be a couple of errors before (or possibly after) the "Assertion failed" line.

**Comment by MrDefacto** [comment]
And here you go...

2016/09/01 01:49:48 [error] 43373#100234: REDIS SCRIPT ERROR: find_channel : @user_script:29: user_script:29: bad argument #1 to 'format' (string expected, got nil)
Assertion failed: (status == NGX_OK), function redis_receive_channel_auth_check_callback, file /usr/ports/www/nginx/work/nchan/src/store/memory/ipc-handlers.c, line 659.
2016/09/01 01:49:48 [alert] 43372#100215: worker process 43373 exited on signal 6

**Comment by slact** [comment]
Ok, thanks, I'll get back to this in an hour or two

**Comment by slact** [comment]
fixed in  18c7150 , thanks for your bug report.

One of the issues with using lots of different Lua scripts on Redis is that the shared code needs to be copied-and-pasted. In this case, I forgot to update one of the copy-paste sections.

Anyway, please re-test to see if this fixes the problem for you.

**Comment by MrDefacto** [comment]
it looka that this bug is gone :-) thx for quick fix
