### ISSUE TITLE
Dynamic 'nchan_message_buffer_length' and 'nchan_message_timeout'

### ISSUE THREAD

**Issue by MrDefacto** [slact/nchan#250]
Hi,

It would be nice to dynamicly control there two variables when publishing messages (for example by http header or in other way like GET parameter). This second value can be even defined per single message not whole queue. 

Of course we can define couple channels from start with different values but it's not possible when channels are defined dynamicly:

	location ~ /pub/(\w+)$ {
	    nchan_redis_pass redis_cluster;
	    nchan_redis_idle_channel_cache_timeout 30s;
	    nchan_publisher;
	    nchan_message_buffer_length 10;
	    nchan_message_timeout 1m;
	    nchan_store_messages on;
	    nchan_channel_id "$1";
	}

Best regards,

**Comment by slact** [comment]
There's something available that half-way what you are asking for. The channel buffer length and message timeout can be adjusted by publishing to differently configured locations. See https://nchan.slact.net/details#publisher-endpoint-configs for an example.

**Comment by MrDefacto** [comment]
Yes i know that i can define different locations. I'm talking about case when on one channel there is need to publish messages with different lifetime each.

second issue is that i don't wanna define for example 100+ locations and need to reconfigure nginx each time when developers make new channel for subscribers :-) 

so there is (\w+) in nginx.conf and it would be nice to give an option for app developers to define dynamicly buffer length and timeout for whole channel (or even better for any single message - when it is published). This would be very powerful.

**Comment by slact** [comment]
This can be done by making     `nchan_message_buffer_length` and `nchan_message_timeout` evaluate nginx variables rather than accept only fixed values. Then you could do something like

```nginx
location ~ /pub/(\w+)$ {
    nchan_publisher;
    nchan_message_buffer_length $arg_buflen;
    nchan_message_timeout $arg_timeout;
    nchan_channel_id "$1";
}
```
then do a `POST /pub/foo?buflen=10&timeout=5m` for the desired effect

> ...it would be nice to give an option for app developers to define dynamicly buffer length and timeout for whole channel (or even better for any single message - when it is published). This would be very powerful.

Per-message timeouts already kind of exist, but with a caveat: A message can only be removed from the old end of the queue. It cannot be deleted if there is still a previous message. In other words, if you publish the following messages with timeouts:
```
hello1 (5m)
hello2 (10s)
hello3 (5m)
```
Message hello2 will remain in the queue until hello1 expires. Then, hello2 will also be deleted immediately.

**Comment by MrDefacto** [comment]
Yes :-) it would be nice. I've even tried such aproach but it was not working :-) that's why i post that idea here...

nginx: [emerg] "nchan_message_buffer_length" directive invalid number in nginx.conf

**Comment by slact** [comment]
half-way there: 8a3f623 . Now the tricky part is to make it work with >1 workers.

**Comment by slact** [comment]
Well, that was easier than expected:  544869e

Feel free to test the (dynamic_buffer)[/slact/nchan/tree/dynamic_buffer] branch and let me know what you find. I'm going to run some more tests as well.

**Comment by MrDefacto** [comment]
it seems that buffer lenght is not working... even if i give 1 it returns more than one value.

`curl --request POST --data "`date`"Content-type: text/script" "http://host/publish/test?timeout=10m&buflen=1"`

second thing it that nginx durning start returns:

```
nginx: [error] MEMSTORE:00: shared_loc_conf_count is 1
nginx: [error] MEMSTORE:00: shared_loc_conf_count is 1
```

**Comment by slact** [comment]
Don't worry about that `shared_loc_conf_count is 1` thing, that's just some temporary debugging info.

Can you show me the nginx config you're using?

**Comment by MrDefacto** [comment]
sure

```
	location ~ /publish/(\w+)$ {
	    nchan_redis_pass redis_cluster;
	    nchan_redis_idle_channel_cache_timeout 30s;
	    nchan_publisher;
	    nchan_message_buffer_length $arg_buflen;
	    nchan_message_timeout $arg_timeout;
	    nchan_store_messages on;
	    nchan_channel_id "$1";
	}
	location ~ /liveinfo/(.*)$ {
	    nchan_redis_pass redis_cluster;
	    nchan_redis_idle_channel_cache_timeout 30s;
	    nchan_subscriber eventsource websocket;
	    nchan_subscriber_timeout 0;
	    nchan_websocket_ping_interval 5;
	    nchan_subscribe_existing_channels_only on;
	    nchan_channel_id "$1";
	    nchan_channel_id_split_delimiter ",";
	}
```

**Comment by MrDefacto** [comment]
maybe this also is relevant... 

```
user www;
worker_processes 8;

timer_resolution 100ms;

events {
    worker_connections 2048;
    use kqueue;
    multi_accept on;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    open_file_cache max=200000 inactive=20s;
    open_file_cache_valid 30s;
    open_file_cache_min_uses 2;
    open_file_cache_errors on;

    sendfile        on;
    tcp_nopush     on;
    tcp_nodelay	on;

    keepalive_timeout  60;

    types_hash_max_size 4096;

    client_body_timeout 60s;

    send_timeout 60s;

    gzip  on;
    gzip_min_length 1024;
    gzip_http_version 1.1;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml application/json application/xml+rss;
    gzip_disable "MSIE [1-6]\.";
    gzip_vary on;
    gzip_comp_level 6;
    gzip_static on;

    nchan_max_reserved_memory 32M;
    nchan_redis_ping_interval 4m;


```

**Comment by MrDefacto** [comment]
sorry... it looks that was some kind of caching problem. i've restarted nginx/redis/clear cache/etc and it looks that buflen work perfectly! :-) great!

**Comment by MrDefacto** [comment]
if only timeout can be set per message it would be amazing ;-)

**Comment by slact** [comment]
> i've restarted nginx/redis/clear cache/etc and it looks that buflen work perfectly! :-) great!

Excellent.

> if only timeout can be set per message it would be amazing ;-)

That's already implemented with the caveat described above, and I don't see a good use case for anything  beyond that. Besides, it's too late at this point to add completel independent per-message expiration (where a message in the middle of the queue with a small TTL can expire and be deleted before older messages), because this would be an API-breaking change. 

I think you'll have to do with dynamic buffer length and timeout variables, which I think it a prety powerful feature as it is. Thanks for suggesting it and helping test it. I'll be including it in the next release.

**Comment by MrDefacto** [comment]
I can give You even two use cases ;-) 
First simple and silly ;-) Clock... Buffer lenght 3... chanel clock... and messages: 'second:' 'minute:' 'hour:' ;-) there is no point to flood channel with seconds and hours... and when new client connects it at start gets every value: 'second' 'minute' 'hours' when... seconds have expiration 1s, minutes 1m, hours 1h...

Second example... my case...
I wanna create info channel. Which will have many variables. One of them will be price ticker which will be refreshed every second.. but there also will be variables refreshed every 2.5m (like crypto block number) and some which can be refreshed very rarely like last client version. 

I don't see how this feature will break API?

**Comment by slact** [comment]
Ah, okay. Both of those can be handled using channel multiplexing. 
Fist example:

```nginx
location = /seconds {
    nchan_publisher;
    nchan_message_timeout 1s;
    nchan_channel_id seconds;
}
location = /minutes {
  nchan_publisher;
  nchan_message_timeout 1m;
  nchan_channel_id minutes;
}
location = /hours {
  nchan_publisher;
  nchan_message_timeout 1h;
  nchan_channel_id hours;
}

location = /clock {
  nchan_subscriber;
  nchan_channel_id seconds minutes hours;
}
```
you can use the same approach for your bitcoin info channel : )

**Comment by MrDefacto** [comment]
Of course :-) now i have similar approach :-) and probably that's the way i must implement this. it will grow js code base on client side (and connections count?).
but still don't know how setting individual per-message timeout will be a problem :-)

and that was just an idea. when we can dynamicly give timeout when publishing to just apply it to every published message individualy.

**Comment by slact** [comment]
> it will grow js code base on client side (and connections count?).

No. Channel multiplexing means you subscribe to multiple channels over a single connection. Read over that example I gave again. The subscriber location subscribes to the second, minute, and hour channels. There is zero client code overhead.

> but still don't know how setting individual per-message timeout will be a problem :-)

It's just a matter of established behavior of Nchan, and the nginx_http_push_module before it. Different messages have different timeouts, but message queues are deleted from oldest to newest, and newer messages are never deleted before older ones, regardless of their TTL. Otherwise, it stopped being a message _queue_ and becomes a message _list_. And the API spec promises a _queue_.

**Comment by MrDefacto** [comment]
ehm... i got it now. Bad promise :-/ it should allow such behavior (in my opinion). it gives more flexibility.

**Comment by MrDefacto** [comment]
imho... can You give me link to specification that forces buffer to be unaltered queue? i google some and in websockets or server-side events specifications can't find such requirement.

**Comment by slact** [comment]
You're quite welcome. If you're feeling generous I do accept bitcoin contributions, check the bottom of the page at https://nchan.slact.net. It sounds like that might be up your alley.

As for the message queue stuff, it's not a websocket requirement, it's just the way Nchan has beenworking for a year now.  This could, of course, be made as a separate option  (`nchan_message_buffer_delete_all_expired_messages` or something more aptly names), but I can't make it the default behavior because of how other users already expect Nchan to function. 

>

**Comment by MrDefacto** [comment]
Seperate option sounds even better! Another great idea from Your side.

p.s.
More Dash alley :-) but of course i'll contribute :-) Do You accept Dash also? ;-)

**Comment by slact** [comment]
Thanks for your contribution! I'll put up a Dash donation address a little later.

I'm closing this issue. Feel free to open any others if you find any problems.

**Comment by MrDefacto** [comment]
Of course :-) if You will decide to add mentioned option it will be great also... thx again.
