### ISSUE TITLE
Nice presentation and asking for more :)

### ISSUE THREAD

**Issue by supertong** [slact/nchan#256]
Hey @slact , it was a nice presentation at Nginx Conf even though I wan't there but I read the slides. :)

The thing I find particularly useful to me in the slides is the Architecture Overview. It really improves my understanding of how Nchan works. However, there is one thing that I would expect to be there is how Nchan delivers message using subscriber pools.

My understanding about the subscriber pool so far is that it groups subscribers by the last message_id they delivered. But I am not quite clear about what the 'walking through red-black tree' does. Is it just getting subscriber pools which is not on the latest message_id and push more messages through? And how does a subscriber propagate from an old message_id pool to a new message_id pool?
For example, we have 4 subscriber pools A, B, C and D, and a subscriber `$` in pool A now. When it propagates,  does Nchan delivery all the messages and then move `$` to pool `D` directly, or does it propagate step by step from A to D.
```
A       B         C            D
$ ---------------------------->$
$ ----->$ -------->$ --------->$
```
Hope I have put my question clearly. The reason I am keen to the knowledge about this is that I found some issue in our Nchan instances where sometimes the Nchan doesn't deliver any message to subscribers. I have seen this issue multiple times but couldn't successfully to reproduce it. I have put in some debug information and can confirm that the the connection between redis and Nchan is OK and Nchan is updating the message queue in memory accordingly, but it just don't deliver message to subscriber. The only solution for now is restarting the Nchan instance..

I guess it could relates to the fact that we are changing the `nchan_message_buffer_length` heavily. For example, from few hundreds message buffer length to only 1 message buffer length. I am not sure what's the impact to those subscriber pool who is not on the latest state.

Hope I can understand this better and put in more debug logs..

Cheers

**Comment by supertong** [comment]
I think it's better to update our infrastructure setup here and maybe you can point me to somewhere. :)

```
   (Nchan Slave)          (Nchan Master)  
       \                           /
                   (Redis)
``` 
Our set up is as simple as above. The master Nchan is the only one that receives publish messages from server. And both master and slave serve messages to subscribers. The issue happens only at Slave instance and it happens after it's been running 10+ hours, so it's a bit difficult to track what happened at that time.

Well, after thinking about it twice. Maybe it's not related to those subscriber pool I described above, since the master is fine.

**Comment by slact** [comment]
Hey, I'm glad you found the talk useful.  I'll link the video as soon as the Nginx Conf team posts all that stuff up on youtube.

> there is one thing that I would expect to be there is how Nchan delivers message using subscriber pools.

I omitted that on purpose, it's too subtle an architectural component for this talk, and isn't essential to understand to get a sense of how Nchan works. But for you I will explain how it fits together.

> My understanding about the subscriber pool so far is that it groups subscribers by the last message_id they delivered.

That's essentially correct. The subscriber pool ("spool") is a grouping of subscribers that all want the same message. Spools are managed by channel "spoolers", which store the spools in a red-black tree. The tree is there to keep spools ordered by message id and to provide O(log N) search time for each spools -- this is needed to retrieve existing spools for incoming subscribers.

When a new spool is created, it sends a call to the storage engine ("store") to actually retrieve the message associated with its message id.  To be more precise, it asks the store for the *next* message associated with its message id.

Once a spool receives a response for its message retrieval request -- and let's say the response is a message -- it forwards it to the subscribers in that spool. Next, the subscribers are transferred to a new spool, the one with the newly received message id, so that subscribers can now receive the following message. (Most often, the previous message id spool actually gets its memory reused, unless there's a spool already present with the current message id).

But a spool need not always receive a message. In fact, whenever you see a subscriber waiting for a message, internally it's because a spool received a MESSAGE_EXPECTED status, and so now it sits around waiting for a message to be published.

This is where I get to your question:

> But I am not quite clear about what the 'walking through red-black tree' does. 

When messages are published to a channel, they are received by the spooler (that's where the spool rbtree is located for each channel). The messages are received with a `message_id` and a `previous_message_id`. That is, a newly published message will be relevant for all subscribers wanting a message in the range between `previous_message_id` and `message_id` (excluding the new `message_id` value itself). This is where walking the rbtree comes in. It's there that all spools within that range are found, and the message is sent to all the matching spools.

There are some other subtleties, like spools forwarding statuses, and subscribers ignoring some of them under some conditions, but that's an even more subtle part that I don't really think is relevant to your question.

**Comment by slact** [comment]
> I think it's better to update our infrastructure setup here and maybe you can point me to somewhere. 
[...] The issue happens only at Slave instance and it happens after it's been running 10+ hours, so it's a bit difficult to track what happened at that time.

The easiest way for me to help out is to have access to your server, grab a debugger, and keep it idle until this problem manifests itself.  Send me an email and we can figure out how to set this up.

**Comment by supertong** [comment]
Thanks @slact for the explanation and the offer. We will def. think about it. For now I will just put in more debug info and see if I can find the bug. Closing this one as this is not a real issue :).
