### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by mhndev** [slact/nchan#279]
this is part of my my /etc/nginx/nginx.conf
which I added server block to my nginx config file from readme file.
```nginx
http {

        ##
        # Basic Settings
        ##

#...
  server {
    #...

    location = /sub {
      nchan_subscriber;
      nchan_channel_id $arg_id;
    }

    location = /pub {
      nchan_publisher;
      nchan_channel_id $arg_id;
    }
  }
```

and when I run following command : curl --request POST --data "test message" http://127.0.0.1:80/pub

I get 404 not found.

**Comment by slact** [comment]
Instead of adding it to `/etc/nginx/nginx.conf`, add the locations to `/etc/nginx/sites-enabled/default` . The Nginx package is configured  to oad server {} blocks from separate files, which are overriding your server {} block in `etc/nginx/nginx.conf`. Here's what you should add to /etc/sites-enabled/default :

```nginx 
    location = /sub {
      nchan_subscriber;
      nchan_channel_id $arg_id;
    }

    location = /pub {
      nchan_publisher;
      nchan_channel_id $arg_id;
    }
```

**Comment by slact** [comment]
Closing this, please reopen if you're still having issues.
