### ISSUE TITLE
worker_connections are not enough

### ISSUE THREAD

**Issue by caseyf** [slact/nchan#346]
This may be a configuration error or misunderstanding on my part but it seems like my resource limits should be more than enough? 8 workers x 32k connections each. This happened after 11 hours of operation

**nginx error log:**

```
2017/04/20 19:43:34 [alert] 9808#0: 32768 worker_connections are not enough
2017/04/20 19:43:34 [alert] 9805#0: 32768 worker_connections are not enough
2017/04/20 19:43:34 [alert] 9808#0: 32768 worker_connections are not enough
2017/04/20 19:43:34 [alert] 9808#0: 32768 worker_connections are not enough
```

**nginx.conf**

```
worker_processes  8;
worker_rlimit_nofile 262144;
events {
    worker_connections  32768;
    use epoll;
}
```

**nchan status**

(these are all websocket subscribers)

```
total published messages: 96925
stored messages: 10
shared memory used: 2576K
channels: 40706
subscribers: 85379
redis pending commands: 0
redis connected servers: 0
total interprocess alerts received: 510156838
interprocess alerts in transit: 0
interprocess queued alerts: 0
total interprocess send delay: 0
total interprocess receive delay: 0
```

**nginx stub status**

```
Active connections: 80720 
server accepts handled requests
 5408702 3824834 3558795 
Reading: 0 Writing: 80641 Waiting: 79 
```

**`netstat -np | grep "/nginx" | awk '{print $6}' | sort | uniq -c`**

```
       16 CONNECTED
  76907 ESTABLISHED
      3 FIN_WAIT1
```

**Comment by slact** [comment]
This is an issue with how nginx distributes the incoming connections between the workers. You should check their distribution rather than the total: 
```
(sudo netstat -antp|grep nginx|awk -F" " '{print $6 $7}'|sort|uniq -c)
```

Nginx doesn't do round-robin failover balancing between the workers. The first worker to try to accept a connection wins (or, alternately, when `accept_mutex` is on, the worker that's holding the mutex wins). If that worker then turns out to be out of worker_connections, tough luck, the connection is closed.

So check the per-worker connection distribution and up the worker_connections to somewhere around the number of open files per process.

**Comment by caseyf** [comment]
Interesting!

After running for a while:

```
1184 ESTABLISHED19232/nginx
   1364 ESTABLISHED19233/nginx
    990 ESTABLISHED19234/nginx
   2190 ESTABLISHED19235/nginx
  30345 ESTABLISHED19236/nginx
   3979 ESTABLISHED19238/nginx
  16623 ESTABLISHED19239/nginx
  30408 ESTABLISHED19240/nginx
```

Shortly after startup:

```
403 ESTABLISHED21177/nginx
   1740 ESTABLISHED21178/nginx
    128 ESTABLISHED21179/nginx
   3602 ESTABLISHED21180/nginx
    130 ESTABLISHED21181/nginx
    171 ESTABLISHED21183/nginx
    425 ESTABLISHED21184/nginx
   5465 ESTABLISHED21185/nginx

```

**Comment by slact** [comment]
yep, it was a fairly recent change. (And EPOLLEXCLUSIVE is almost certainly the best option.)
