### ISSUE TITLE
Unexpected behaviour when using nchan_subscribe_request & nchan_unsubscribe_request

### ISSUE THREAD

**Issue by mueller-berlus** [slact/nchan#374]
Hi,

first of all, thanks for the great work. 
I am testing the sub/unsub hook to implement a presence feature. Unfortunately I had no luck sofar, because they behave different from what I would expect. I am using Ubuntu 16.04 with the nginx packages you provide on your page. I am using WebSockets to connect to nchan.

nchan_subscribe_request: Using this option blocks the WebSocket. No messages get through and the hook is not called. Except imitatively after opening or closing the WebSocket. Immediately after opening all messages on the server are replayed. Immediately after closing the WebSocket the sub hook is called.

nchan_unsubscribe_request: Using this option together with nchan_subscribe_request leads to unsub hooks only being called after subscribers timeout.
Using the option without nchan_subscribe_request leads to the hook being called once with one channel id, even if the connection subscribed to multiple channels. Is this expected behavior, meaning that one has to use one WebSocket per channel?

Here is my configuration:
```
        location /broadcasting/proxy/auth {
                proxy_pass http://localhost/broadcasting/auth;
                proxy_pass_request_body off;
                proxy_set_header Content-Length "";
                proxy_buffers 128 4k;
                proxy_buffer_size 128k;
                proxy_busy_buffers_size 128k;
        }

        location /broadcasting/events {
                nchan_pubsub;
                nchan_authorize_request /broadcasting/proxy/auth;
                nchan_subscribe_request /broadcasting/proxy/sub;
                nchan_unsubscribe_request /broadcasting/proxy/unsub;
                nchan_channel_id $arg_channels;
                nchan_channel_id_split_delimiter ",";
                nchan_channel_group mygroup;
                nchan_message_buffer_length 50;
                nchan_message_timeout 5m;
        }

        location /broadcasting/proxy/unsub {
                proxy_pass http://localhost/broadcasting/unsub;
                proxy_ignore_client_abort on;
                proxy_set_header X-Channel-Id $nchan_channel_id;
        }

        location /broadcasting/proxy/sub {
                proxy_pass http://localhost/broadcasting/sub;
                proxy_set_header X-Channel-Id $nchan_channel_id;
        }

```

Any comment would be greatly appreciated.

**Comment by slact** [comment]
This is a bug. Looks like `nchan_authorize_request` is interfering with the nchan_subscribe_request / nchan_unsubscribe_request cycle. 

I'll be fixing this shortly. Meanwhile, you should omit `nchan_subscribe_request` as `nchan_authorize_request` performs a nearly identical function except with the ability to decline the incoming subscriber.

Let me know if the temporary solution addresses your problem. Meanwhile, I'll update this when I have a fix ready.

**Comment by mueller-berlus** [comment]
Yes. ```nchan_authorize_request``` fits my needs, so I am not in a hurry.

**Comment by alabeduarte** [comment]
Hi there,

I'm just having a similar issue here, are there any updates?

Cheers!

**Comment by gtramontina** [comment]
Acknowledging this issue, and following up on https://github.com/slact/nchan/issues/395#issuecomment-331364816, do you have any suggestion on notifying upstream that an authorized connection has just established? The use case we have is:

1. Client attempts to subscribe to a private channel;
2. Nchan talks to an authorization upstream server and gets a `200` back;
3. Client connection is established;
4. Nchan talks to a presence upstream server to notify that a connection has just been established;
5. The presence upstream server publishes "unread" messages to that channel. It is worth mentioning we've deliberately disabled the nchan's message persistence because we have some business rules around when certain messages should be delivered (if ever, as they might be irrelevant after a certain amount of time).

What we're trying to do is:

1. As soon as we know the response from the authorization upstream, we return back to the client so the connection can be established.
2. Asynchronously, _after_ the previous step, send a subrequest to the presence upstream.

To help on the async subrequest, we tried the following using `content_by_lua_block` like so:

```nginx
location = /upstream/auth_and_presence {
    internal;
    content_by_lua_block {
      auth_url = '/upstream/auth'
      if ngx.var.is_args == "?" then
        auth_url = auth_url .. ngx.var.is_args .. ngx.var.args;
      end

      ngx.status = res.status
      ngx.say()
      ngx.eof()

      res = ngx.location.capture(auth_url);
      if res.status == ngx.HTTP_OK then
        ngx.location.capture('/upstream/presence')
      end
    }
  }

location = /upstream/auth { … }
location = /upstream/presence { … }
```

This didn't work well, as it seemed the connection was only established _after_ the presence upstream was notified. Causing the presence upstream to send messages to a channel with `0` subscribers.

We've just started experimenting with https://github.com/openresty/echo-nginx-module#echo_location_async and https://github.com/openresty/echo-nginx-module#echo_subrequest_async.

We managed to get the order of the events right (`"Authorized" >> "Connection Established" >> "Subscribed"`), but, for some reason, we're not receiving messages anymore. Below is the response we get from Nchan after `POST`ing to the `private_channel` where, supposedly, the subscription happened successfuly (as we can see `active subscribers: 1`):

```sh
$ http POST http://localhost:8081/pub/private_channel
HTTP/1.1 201 Created
Connection: keep-alive
Content-Length: 100
Content-Type: text/plain
Date: Fri, 22 Sep 2017 07:31:38 GMT
Server: nginx/1.12.1

queued messages: 0
last requested: 0 sec. ago
active subscribers: 1
last message id: 1506065498:0
```

Any help is much appreciated! (I apologize for the lengthy message)

**Comment by slact** [comment]
The issue has been fixed in master in commit a840847b.

**Comment by alabeduarte** [comment]
Hi @slact 

Thank you so much for the quick answer and action! I'll verify cloning the repo, run the tests against the master branch and I'll give you a feedback.

Cheers.

**Comment by slact** [comment]
> do you have an estimation for the new release?

I have a few more fixes and some small features left to add to this one, so I would say a week or two.

**Comment by alabeduarte** [comment]
Hi @slact 

After a lot of testing, it's really working and suiting our needs. Again, thank you for the great work and looking forward to the next release!

*cc/ @gtramontina*
