### ISSUE TITLE
Authorization errors becoming 500

### ISSUE THREAD

**Issue by gtramontina** [slact/nchan#395]
Hi there! First off, thanks a lot for `nchan`! We slowly started using it in production and now we're expanding its usage, so thanks a lot! Now, onto the issue… 😃

The nchan docs for [nchan_authorize_request](https://nchan.io/#request-authorization) says:

> This feature, configured with nchan_authorize_request, behaves just like the Nginx http_auth_request module. (…) If authorized, it should respond with an empty 200 OK response. Otherwise, respond with a 403 Forbidden, which this will be forwarded to the client and the requested action will be aborted.

And nginx docs for [http_auth_request](https://nginx.org/en/docs/http/ngx_http_auth_request_module.html) says:

> (…) If the subrequest returns a 2xx response code, the access is allowed. If it returns 401 or 403, the access is denied with the corresponding error code. Any other response code returned by the subrequest is considered an error.

Based on that, we went ahead and implemented our auth upstream to return `403` when 👎 and `200` then 👍. Thus, we were expecting a `403` back on the client, but kept getting `500` no matter what. Puzzled by this behavior, we decided doing a little digging and found the following:

In the tests, the `authserver` is returning  `403`:
https://github.com/slact/nchan/blob/05d6a762b7c285a34925cd7d3ac411d8ce33f9e3/dev/authserver.rb#L62-L63

But the assertion is against `500`:
https://github.com/slact/nchan/blob/05d6a762b7c285a34925cd7d3ac411d8ce33f9e3/dev/test.rb#L1093

So, apparently, this is by design. Should this be considered a code bug, or just a matter of updating the documentation? I'd consider this a bug, given that it seems it was intended to mimic `http_auth_request`'s behavior (or perhaps nginx is misbehaving?).

Cheers!

<sub>_ping @alabeduarte_</sub>

**Comment by slact** [comment]
The 500 error shows up when the auth request cannot be completed -- usually because the server can't be reached.

That's the meaning of the 500 check in [test_auth](https://github.com/slact/nchan/blob/05d6a762b7c285a34925cd7d3ac411d8ce33f9e3/dev/test.rb#L1082). That first test is trying to do an auth request without an upstream auth server running.

The real auth test is on line [1115](https://github.com/slact/nchan/blob/05d6a762b7c285a34925cd7d3ac411d8ce33f9e3/dev/test.rb#L1115). And it passes.

I also double-checked by hand and subscribers do indeed receive a 403 on authorization failure. So my guess is that Nginx for some reason cannot complete the request to your auth server.

**Comment by gtramontina** [comment]
Hum… right. I guess you're right. We were using a lua block to notify upstream that a user has connected as an attempt to workaround https://github.com/slact/nchan/issues/374. This lua block was exiting, thus nginx was `500`'ing… Closing this as a false alarm. Sorry! 😄
