### ISSUE TITLE
need advice

### ISSUE THREAD

**Issue by RuslanValitov** [slact/nchan#497]
Hi.
Can anyone answer my few question?
I trying make web online chat between clients and operators (let's call them users or user1, user2).
1. Should I make separate channels: one for user1, and one for user2, and make communication between them by sending messages from one channel to another (from user1 to user2)?
So each user will have it own channel, secured by password and user name (and another user can't access it). User1 can read all recived messages from all another USERs in his channel. And can send message to all another users, in to users channals.
2. Second way: user1 and user2 are use one shared channel. When user1 subscribe, user2 need to subscribe to this channel too. In this case users endpoints will not be secure, and any other user (user3,user4,user5,...) can connect shared channel, and read messages from user1 and user2.
So which way is better?
3. The third question: my clients use websocket client. In case1 when I have two endpoints: one for subscribe (somewebsite.com/sub?id=user1), and one for publishing (somewebsite.com/pub?id=user2) websocket client can't publish and subscribe from two different endpoints?!
This why I need to subscribe user1 by websocket client on (somewebsite.com/sub?id=user1), and send message to user2 (somewebsite.com/pub?id=user2) only by http post method, websocket client will be unusefull to publish message in another user channel.
Am I right?
4. In case2 when I have one endpoint with shared channel (somewebsite.com/pubsub?id=user1user2) I can use websocket client and to recive (subscribe) message, and to publish message over one websocket connection.
Please correct me if I understand something wrong!

Thank you very much, expecting on your help in understanding nchan.
Regards Ruslan.

**Comment by ivanovv** [comment]
I think the basic rule is simple – if you want two users to communicate then you create a channel for them. If you want all users to communicate – you create a shared channel. Don't be afraid to create channels, they are chip unless we are speaking of a system at scale of 20K users at the same time.

Now, about channel security. One way to do it is just to use long random channel names that only users you want to connect will know. Sort of like an API key. But that's in case when you have to deal with users that your web application knows nothing of, like anon users. If the users are registered with your app (in web parlance that basically means they have your cookie) you can always check if the user has the right to access the channel via auth callback. 

HTH

**Comment by RuslanValitov** [comment]
> I think the basic rule is simple – if you want two users to communicate then you create a channel for them. If you want all users to communicate – you create a shared channel. Don't be afraid to create channels, they are chip unless we are speaking of a system at scale of 20K users at the same time (the channels are still chip, but maybe you will have to tune the server OS settings, not sure).
> 
> Now, about channel security. One way to do it is just to use long random channel names that only users you want to connect will know. Sort of like an API key. But that's in case when you have to deal with users that your web application knows nothing of, like anon users. If the users are registered with your app (in web parlance that basically means they have your cookie) you can always check if the user has the right to access the channel via auth callback.
> 
> HTH

Thank you for your reply Victor. Basically I get it. 
But how it will be in case:
1. One operator must talk with 2,3,4...10.. users? Should I create 2,3,4...10... websocket connections from one operator to each user? 
user1<->SSE<->NGINX(nchan)<=>websocket1<=>operator1
user2<->SSE<->NGINX(nchan)<=>websocket2<=>operator1
user3<->SSE<->NGINX(nchan)<=>websocket3<=>operator1
user4<->SSE<->NGINX(nchan)<=>websocket4<=>operator1
user5<->SSE<->NGINX(nchan)<=>websocket5<=>operator1
user6<->SSE<->NGINX(nchan)<=>websocket6<=>operator1
user7<->SSE<->NGINX(nchan)<=>websocket7<=>operator1
user8<->SSE<->NGINX(nchan)<=>websocket8<=>operator1
user9<->SSE<->NGINX(nchan)<=>websocket9<=>operator1
user10<->SSE<->NGINX(nchan)<=>websocket10<=>operator1
after (for example) user4 close SSE connection, operator will also close websocket connection on his side?
In this case it not a shared channels, and not communication between two users. I think it some kind one to multi connection, but all channel must be isolated between users.
Or there is another implementation advice?

2. To use auth callback in nchan doc need to use proxy_pass to upstream_app, and I use lua +ngx.exec:
location /onlinechat {
content_by_lua '
....
//checking session id in redis, or get some data from redis to authenticate user, and generate channel_id 		
ngx.exec("/intchat/channel_id");
....
//or return 403: Forbidden for example if there is no session id in redis
';
}

location ~ /intchat/(\w+)$ {
internal;
nchan_pubsub;
nchan_channel_id $1;
}

This way look very easy, work fine for me. I do not need to use heavy php backend.
Does this solution bad way in your opinion?

Thanks you.
Regards Ruslan.

**Comment by ivanovv** [comment]
> In this case it not a shared channels, and not communication between two users. I think it some kind one to multi connection, but all channel must be isolated between users.
> Or there is another implementation advice?

You want to take a look at the connection multiplexing feature. It basically allows up to 255 channels per one connection.


Or you might want to build your own multiplexing solution (something like what Pusher has) when single websocket connection is used to emulate any number of channels, you will have to write the message routing code yourself though.

The truth is – I have almost zero experience building online chats, so if I were you I would just google some solutions first, and then would try to fit something to your usecase.

One thing that I would also suggest is taking a look at other solutions, both open source and proprietary. 

Proprietary: Pusher.com is something everyone has heard of, and I bet there are alternatives. 

Open Source: Elixir/Phoenix, other Erlang based chats. Again, I don't know many projects in that niche, but my rule of thumb would be using something mature, written in a language that has excellent concurrency options (erlang/elixir, go, node) and steering away from php/ruby/other interpreted languages with poor concurrency support. 

Nchan is a great fit if you know C and nginx internals, then it will be very easy for you to fix bugs that might appear.


> This way look very easy, work fine for me. I do not need to use heavy php backend.
Does this solution bad way in your opinion? 

I don't really have a strong opinion here, because basically this is how I see it – if you are going to deal with 5K RPM (`requests per minute`) for that specific endpoint (like, your site is very popular, or you have some sort of timed events and users will connect basically at the same time, within a couple of minutes), then it makes sense to bother if the perf will be good or not. If it is like 1000 RPM (or less) then just go with the easiest solution and that's it.

One thing I will point out though is that you basically have zero visibility into your auth process here (`nchan` is a black box, `nginx` is a black box). So to debug the first implementation and to resolve issues that might emerge later on you will have to deal with `nginx` debug log (or some other way to log the things that might interest you). When you have the auth endpoint as a php script at least you will see requests to that endpoint in your app server log.

**Comment by yellow1912** [comment]
This is old, but if you rely on php, try out the swoole extenstion to handle requests.
