### ISSUE TITLE
Include channel ID in messages sent to multi-channel subscription

### ISSUE THREAD

**Issue by JamieCressey** [slact/nchan#562]
Creating a multi-channel subscription

```
curl -N --http2 -H "Accept:text/event-stream" http://localhost:8080/multisub-split/test,foo
```

And publishing a message to one of these channels;

```
curl --request POST --data "test message" http://127.0.0.1:8080/pub/test
```

The subscriber receives only the message payload and no way to identify which channel the message came from;

```
id: 1586620510:[0],-
data: test message
```

Is there a way to include the channel ID (in the case; `test`) in the messages sent to multi-channel subscribers?

**Comment by neben** [comment]
It is already included in the `id`, see explanation below.

The `id` field accompanying a message is composed of several parts. The number before the colon is the time the message was received by the server (as a unix timestamp). The string after the colon resembles the list of channels in the order they were subscribed to. The channel receiving the current message is indicated by a number in brackets. The number resembles the count of received messages on this channel during the current second (indicated by the timestamp). Channels not having received a message in this 1-second time slot are represented with a dash, whereas counters without a dash indicate that there has been another message on a different channel in the same time slot.

So your `id` says: This message was received by the server on Saturday, 11-Apr-20 15:55:10 UTC, on channel `test`, and it was the first message received in this 1-second interval.

**Comment by slact** [comment]
I couldn't have explained it better myself, @neben , thanks!
I never documented the message id format because I expected it would be subject to change in the future, but at this point I think at least the timestamp is here to stay. The numbers that follow might get a different syntax in the future to handle large channel multiplexings -- it gets unwieldy for >20 channels. The basic structure, though, has so far stood the test of time, so I will be documenting it and making it part of the API promise in a future release.
