### ISSUE TITLE
Deleting a PubSub endpoint

### ISSUE THREAD

**Issue by emschwartz** [slact/nchan#587]
Sending an HTTP `DELETE` to a PubSub endpoint returns a 405 error.

Would it be possible to support explicitly deleting PubSub channels in the same way that you can delete normal channels by sending a `DELETE` request to the publisher endpoint (or is there a reason this would be a bad idea)?

**Comment by slact** [comment]
The `publisher` endpoint is designed for back-end access which allows destructive operations. `subscriber` and `pubsub` endpoints are designed with public consumption in mind, which is why `DELETE`s are not available on `pubsub`. 

I could see adding an option for it, but this complicates the documentation even further. I recommend developers use a separate `publisher` location that they can use to DELETE channels as needed. There's no overhead for sending a request to a different URL, and the only extra effort required here is adding a location to the Nginx config.

**Comment by emschwartz** [comment]
Ah I see. I happen to have a use case where channel creation (and deletion) is public but I can see how that's not the norm.

If I used separate locations as you suggest, there wouldn't be a way to send and receive messages via a single WebSocket connection, right?

**Comment by slact** [comment]
I think you misunderstood my suggestion. You should set up two public-facing locations:
```
location ~/channel/(\w+)/pubsub {
  #use this for bidirectional websocket communication
  nchan_channel_id $1;
  nchan_pubsub;
}
location ~/channel/(\w+)/publish {
  #use this to DELETE channels
  nchan_channel_id $1;
  nchan_publisher;
}
```

**Comment by emschwartz** [comment]
Ohh, got it. That works!

Thanks -- and thanks for all of your work on nchan!
