### ISSUE TITLE
Nchan nchan_subscriber_first_message is not working

### ISSUE THREAD

**Issue by car1ot** [slact/nchan#595]
I don't need to receieve old messages on clients. I only need to get the newest since connection made.
I've setted nchan_subscriber_first_message newest; and restarted nginx server, but this haven't made any affect.

**Comment by emschwartz** [comment]
When you say it hasn't made any affect, do you mean that you're seeing older messages first or are you not seeing any messages at all?

I thought the `nchan_subscriber_first_message newest` setting was behaving oddly (https://github.com/slact/nchan/issues/590) but hadn't realized that `newest` would _only_ send messages that are sent after the subscriber subscribes (rather than the most recent messages sent at any point). It sounds like that's the behavior you want though so I'm curious what the exact issue is.

**Comment by slact** [comment]
I haven't been able to reproduce this -- `nchan_subscriber_first_message newest` works as intended in my tests
