### ISSUE TITLE
Make Memcached available as a message store

### ISSUE THREAD

**Issue by slact** [slact/nchan#7]
How useful would this be? One could then run a completely distributed long-polling NHPM network.

**Comment by slact** [comment]
Not gonna happen, memcached doesn't do pub/sub. Besides, there's Redis support now.

**Comment by xwiz** [comment]
I'll just like to add that Redis is quite bug prone mainly because it tries to do too much. Ideally, it's better to write a mini driver for flushing to disk and add cluster functionality directly to nchan than relying on Redis. I don't really see why one has to rely on another software to scale Nchan.

**Comment by xwiz** [comment]
So I just happened to remember [KeyDB](https://github.com/Snapchat/KeyDB) is trying to solve some of the pitfalls of Redis, I strongly believe Nchan will benefit better from focusing on KeyDB support rather than Redis since KeyDB supports the same APIs. This can at least give a close performance alternative to a manual mcrouter/memcached implementation.
