### ISSUE TITLE
Support for X-Accel-Redirect with posting messages

### ISSUE THREAD

**Issue by metrixsean** [slact/nchan#79]
Would it be possible to all X-Accel-Redirect support with posting messages?

I think this could be handled if the configuration file used a custom header.

location = /internal/pub {
  internal;
  set $push_channel_id $arg_channel_id;
  push_publisher;
 
  add_header "X-Body" $request_body;
}

Then the module would be able to check for this using the GET path.

I'm trying to add an authenticated layer in front of the push_publisher block.

**Comment by slact** [comment]
Subscriber (and publisher) authorization can now be handled with the `nchan_authorize_request` <url> config directive. I don't think the X-Accel-Redirect workaround is necessary anymore.

**Comment by amcgregor** [comment]
Hmm. This would appear to solve the problem in a very different direction than hoped.  The flow for my applications would then be: event consumer hits an authenticated application URL (where credentials have already been loaded and verified) to determine the push endpoint, visibly redirects the consumer to the naive endpoint with large entropy-filled channel identifier, the endpoint then makes a sub-request back into the application to determine if endpoint access is authorized.  :-1: 

This seems… excessive.  I unfortunately can't skip the "resolve where the endpoint is" step because push endpoints are scaled with front end load balancers, not application nodes, and the associations between user session and push endpoint server need to be tracked.  X-Accel-Redirect is less of a workaround and more of an optimization, saving potentially quite a few database roundtrips by getting them all out of the way at the start.  While such a callback is "generally" useful, it sadly doesn't cover my use cases and introduces complexity (and roundtrips) where there need not be any.  It also does nothing to resolve the channel ID exposure issue previously mentioned.

**Comment by slact** [comment]
Eeh, that does make sense. `nchan_authorize_request` is primarily for publishing and subscribing to shared channels, not authenticating per-user channels. I'm not sure I need to do any extra work to get X-Accel-Redirect working, and I don't think I'll have it for the upcoming release, but I'll do some testing. 

Of course, there are ways to encourage me. (This is where I rattle my tip jar.)

**Comment by slact** [comment]
I just tested it and X-Accel-Redirect works just fine.

**Comment by amcgregor** [comment]
Cool beans.  Back in the day (when I first commented on this ticket) it had some interesting side-effects; notably Nginx wouldn't keep the connection open for the expected period of time when long-polling.

You mentioned a tip jar, and I did search for one, but neither your Github profile nor site point to anything for the purpose.  ;)

**Comment by slact** [comment]
Back in those days the way I was delaying requests was a bit hacky, so that might have been where the side-effects came from.

And I'm still working on the nchan web site, and haven't put up tip jar links there yet. (Only half the documentation is finished and I still have some proofreading to do after that) All that stuff is still over at https://pushmodule.slact.net . There's a paypal link there, and I also accept bitcoin at `1NHPMyqSanG2BC21Twqi8Pf1pXXgbPuLdJ` . 

Thank you for your interest and useful feedback.
