### ISSUE TITLE
`push_min_message_recipients` not formally documented

### ISSUE THREAD

**Issue by mkonecny** [slact/nchan#97]
It is seen in the example config, however it is missing from the list of available commands.

**Comment by mkonecny** [comment]
pull request created here: https://github.com/slact/nginx_http_push_module/pull/98

**Comment by slact** [comment]
First off, good find. You've got a pretty good eye for consistency. This is indeed an issue, but I want to resolve it differently. Rather than document it, I will instead remove the *push_min_message_recipients* parameter from the example config. In future versions, this undocumented functionality is going to disappear altogether.

Here is why: I'm building up the push module to be a distributed caching proxy for websocket and pub/sub servers. Deleting a message after it has been consumed some given number of times means that requests for messages are not idempotent -- that is, they cannot be repeated without side effects. Therefore, a GET would not be appropriate for a non-idempotent action of retrieving a message from a channel, and furthermore would become impossible to cache by a unidirectional, request-only proxy. Because better proxying is exactly where I'm taking the push module, exposing this feature would really, really complicate the code. Idempotent actions are easy to cache, others are what computer scientists tongue-in-cheek call nontrivial, i.e. a bitch to implement.  This is kind of like how HTTP proxies do not cache POST requests, because repeat requests result in a state change on the server.

I should have excised this option sooner, but one of the early users of the push module used it when I was still wrapping my head around what kind of flexibility should be exposed to the user. It's basically there for legacy support. Since I'm rewriting the entire storage engine (check out what's going on in the redis and redis-WIP branches), this feature is going to disappear quite soon.

I cannot think of any use cases for this feature that could not be implemented in some other way. If you need it for some particular application, let me know, and I can help you come up with a workaround. Or if you disagree entirely, I'd also like to hear out that case.

Thanks for your attention and your eye for detail.

**Comment by mkonecny** [comment]
I guess in that case `push_delete_oldest_received_message` should be deleted as well? 

Personally I believe that removing both these is the correct approach, but it might make sense to make a huge version jump or new branch if it's going to break backwards compatibility. 

I think that a lot of Debian/Ubuntu users use this project because it's included in the `nginx-extras` package. Such a change would probably break everyone's setup with the next OS update.

Your thoughts?

**Comment by slact** [comment]
Like I said, you've got an eye for consistency : )

Yes, *push_delete_oldest_received_message* will be deprecated as well. And yes, this is going to violate backwards compatibility, but I don't think it'll break anything serious. Using this option is not recommended in the documentation (and I'll be officially deprecating it), and besides the functionality of preserving a full queue of unseen messages could be used as a denial-of-service attack by forcing the server to never clear messages on a private channel and having it run out of memory. 

Once a message expires, it should be up for deletion, regardless of whether it was consumed. Once a channel queues too many messages, the oldest beyond max. queue length should be deleted, also unconditionally.

*push_delete_oldest_received_message*  and *push_min_message_recipients* are my design errors in the message storage system. I've kept both around because it wasn't worth breaking backwards compatibility, but the upcoming release is going to have a lot more features to warrant this break from history. I'll also be deprecating a few other options, but they're just going to be reconceptualizations with equivalent functionality made available from a more orthogonal set of config parameters. For example, the concurrency (broadcast/first-in/last-in) is out, but will be replaced by max_clients_per_channel or some such.

For the Debian/Ubuntu users, there will be plenty of warning, and I hope the upcoming feature set will far outweigh the hassle of transition.

**Comment by slact** [comment]
yeah, these are deprecated now.
